routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/','IndexController@show');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/surveydashboard', 'SurveyDashboadrController@index')->name('surveydashboard');
Route::get('/surveydashboard/{id}', 'SurveyDashboadrController@Questionform')->name('question-form');
Route::post('/createpatientanswer/{id}','SurveyDashboadrController@CreatePatientAnswer')->name('create-patient-answer');
Route::get('/showanswerresult/{id}/{patient_id}','SurveyDashboadrController@ShowAnsweRresult')->name('show-answer-result');

Route::get('/patientlist','SurveyDashboadrController@Showpatientlist')->name('show-patientlist');
Route::delete('/destroypatient/{id}', 'SurveyDashboadrController@destroyPatient')->name('destroypatientlist');

//search
Route::post('/search','SurveyDashboadrController@AutocomplitSearch')->name('autocomplete.search');

//pdf
Route::get('/downloadPDF/{id}/{patient_id}','SurveyDashboadrController@downloadPDF')->name('download-pdf');
// more data
Route::post('/addajax', 'SurveyDashboadrController@ShowWithAjax')->name('addajax');


Route::get('/patients', 'PatientController@ShowPatientsList')->name('add-patient');
Route::post('/patients', 'PatientController@CreatePatientsList')->name('create-patient');
Route::post('/createanswer','PatientController@CreateAnswer')->name('create-answer');



//admin
Route::group(['middleware' =>'admin'], function() {
    Route::resource('/admindashboard', 'AdminController');
    Route::get('/showcat', 'AdminController@ShowCat')->name('showcat');
    Route::get('/showallcat', 'AdminController@ShowAllCat')->name('showallcat');

//question
    Route::get('/showquestion/{id}', 'AdminController@ShowQusetion')->name('showquestion');
    Route::post('/addquestion', 'AdminController@createQuestion')->name('create-question');
    Route::get('/addquestion/{id?}', 'AdminController@addQuestion')->name('add-question');
//    subquest
    Route::get('/addquestion/{id}', 'AdminController@addsubQuestion');
    Route::get('/editquestion/{id}', 'AdminController@editQuestion')->name('edit-question');
    Route::post('/editquestion', 'AdminController@storeQuestion')->name('edit-question');
    Route::delete('/destroyquestion/{id}', 'AdminController@destroyQuestion')->name('destroyquestion');

////addansweradmin

    Route::get('/addanswer/{id}', 'AdminController@addAnswer')->name('addanswer');
    Route::get('/deleteanswer/{id}', 'AdminController@deleteAnswer')->name('deleteanswer');
    Route::post('/createanswer', 'AdminController@CreateAnswer')->name('create-answer');

});

resources/views/admin/add-answer.blade.php
@extends('admin.leftsidebar')

@section('content')
    <div class="row content_answer">
        <div class="content-wraper">
            <div class="container-fluid">
                <div class="row answer_form_content">
                    <div class="create_answer_form col-md-12">

                        <div class="alert alert-info" role="alert">
                            Create answers for  "{{$question->question}}" question
                        </div>
                        <form action="{{route('create-answer')}}" method="post" enctype="multipart/form-data">
                            <div class="form-group desk_label col-md-8">
                                <input type="hidden" name="question_id" value="{{$question->id}}">
                                <label for="exampleInputPassword1">Create Answer</label>

                                <div class="input-group mb-3">
                                    <input type="text" name="description" class="form-control" id="exampleInputPassword1" placeholder="">
                                    <div class="input-group-prepend">
                                        <button type="submit" class="input-group-text" id="basic-addon1 add_btn_answer">Add</button>
                                    </div>
                                </div>
                            </div>
                            {{csrf_field()}}
                        </form>
                    </div>
                    @if($question->answers->count()>0)
                    <div class="added_answers">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Choices</th>
                                    <th scope="col">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($question->answers as $key=>$answer)
                                    <tr>
                                        <th scope="row">{{$key+1}}</th>
                                        <td>{{$answer->description}}</td>
                                        <td>
                                            <a class="btn btn-danger" href="{{url("deleteanswer/".$answer->id)}}" onclick="return confirm('Are you sure?')">delete</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                    </div>
                    @else
                        <div class="clearfix  col-md-12">
                            <div class="alert alert-warning" role="alert">
                                There Is No Any Answers Yet
                            </div>
                        </div>
                    @endif


                </div>
            </div>


        </div>
    </div>
@endsection

resources/views/admin/add-qusetion.blade.php
@extends('admin.leftsidebar')

@section('content')

<div id="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <form action="{{route('create-question')}}"  method="post" enctype="multipart/form-data">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if(is_null($id))
                        <div class="form-group">
                                <label for="exampleFormControlSelect1">Please Select Survey</label>
                                <select class="form-control" id="exampleFormControlSelect1" name="cat_id" required {{ !is_null($id) ? "disabled" : "" }}>
                                    @foreach($survey as $sur)
                                        {{--{{dd($sur)}})--}}
                                        <option value="{{$sur->id}}">{{{$sur->cat}}}</option>
                                    @endforeach
                                </select>
                        </div>
                    @else
                       @if (!is_null($question) )
                            <input type="hidden" name="parent_id"  value="{{$question->id}}"   required>
                            <input type="hidden" name="cat_id"  value="{{$question->cat_id}}"  required>

                            <div class="alert alert-info">
                                    <strong>{{$question->question}}</strong>
                            </div>
                        @endif
                    @endif
                    <div class="form-group">
                        <label for="exampleInputPassword1">Write Question Description</label>
                        <input type="text" name="question" class="form-control" id="exampleInputPassword1" placeholder="" required>

                    </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1"> Select Type Of Question</label><br>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="1" class="form-check-input" required> <label>Qustom Question</label>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="2" class="form-check-input" required> <label>With Single Choice </label>
                            </label>
                        </div>
                        <div class="form-check disabled">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="3" class="form-check-input" required> <label>With Multiple Choice</label>
                            </label>
                        </div>

                        @if(is_null($id))
                                <div class="form-check disabled">
                                    <label class="form-check-label">
                                       <input type="radio" name="type" value="4" class="form-check-input" required> <label>Has Subquestions</label>
                                    </label>
                                </div>
                         @endif

                        </div>
                    <button type="submit" class="btn btn-primary">Add Question</button>
                    {{csrf_field()}}
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/allcategory.blade.php
@extends('admin.leftsidebar')

@section('content')
    <div class="survey_content">
        <table id="example" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>
                    survey
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($category as $cat)
                <tr>
                    <td>
                        <div class="survays_right_box_top">
                            <div class="survays_right_box_top_right"></div>
                            <a href="{{route('showquestion',$cat->id)}}"><p class="survey_p answer">{{$cat->cat}}</p></a>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/create.blade.php
@extends('admin.leftsidebar')

@section('content')
    <div id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="add_category">
                        <h4>Add  Survey</h4>
                    </div>
                    <form action="{{route('admindashboard.store')}}"  method="post" enctype="multipart/form-data">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="exampleInputPassword1"> Survey</label>
                            <input type="text" name="cat" class="form-control" id="exampleInputPassword1" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Description</label>
                            <input type="text" name="description" class="form-control" id="exampleInputPassword1" placeholder="">
                        </div>

                        <button type="submit" class="btn btn-primary add_category_btn">Add</button>
                        {{csrf_field()}}
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.leftsidebar')

@section('content')

@endsection

resources/views/admin/edit-qusetion.blade.php
@extends('admin.leftsidebar')

@section('content')

<div id="content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <form action="{{route('edit-question')}}"  method="post" enctype="multipart/form-data">
                    <input type="hidden" name="id" value="{{$question->id}}">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                            <label for="exampleFormControlSelect1">Please Select Survey</label>
                            <select class="form-control" id="exampleFormControlSelect1" name="cat_id">
                                @foreach($survey as $sur)
                                    <option value="{{$sur->id}}" {{ $question->cat_id == $sur->id ? "selected='selected'" : "" }} > {{{$sur->cat}}}</option>
                                @endforeach
                            </select>
                     </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Write Question Description</label>
                        <input type="text" name="question"  value="{{$question->question}}" class="form-control" id="exampleInputPassword1" placeholder="">
                    </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1"> Select Type Of Question</label><br>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="1" {{ $question->type == \App\Question::QUSTOM_QUESTION ? "checked='checked'" : "" }} class="form-check-input"> <label>Qastom Question</label>
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="2" {{ $question->type == \App\Question::WITH_SINGLE_CHOICE ? "checked='checked'" : "" }} class="form-check-input" > <label>With Single Choice </label>
                            </label>
                        </div>
                        <div class="form-check disabled">
                            <label class="form-check-label">
                                <input type="radio" name="type" value="3" {{ $question->type == \App\Question::WITH_MULTIPLE_CHOICE ? "checked='checked'" : "" }} class="form-check-input" > <label>With Multiple Choice</label>
                            </label>
                        </div>

                        </div>
                    <button type="submit" class="btn btn-primary">Edit Question</button>
                    {{csrf_field()}}
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.leftsidebar')

@section('content')
    <div id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <form action="{{route('admindashboard.update',$sur->id)}}"  method="post" enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="exampleInputPassword1"> Survey</label>
                                <input type="text" name="cat" class="form-control" id="exampleInputPassword1"  value="{{$sur->cat}}">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Description</label>
                                <input type="text" name="description" class="form-control" id="exampleInputPassword1" value = "{{$sur->description}}">
                            </div>
                                <button type="submit" class="btn btn-success">Update</button>
                            {{csrf_field()}}
                    </form>
                </div>
            </div>
        </div>
        <hr>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('admin.leftsidebar')

@section('content')


@endsection

resources/views/admin/leftsidebar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Dashboard</title>
    <!-- Bootstrap core CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin/vendor/bootstrap/css/bootstrap.min.css')}}"/>
    <link  href="{{asset('admin/vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->

    <link  href="{{asset('admin/css/style.css')}}"  rel="stylesheet">

    <link  href="{{asset('admin/css/sb-admin.css')}}" rel="stylesheet">
</head>

<body id="page-top">
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">



    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left Side Of Navbar -->
        <ul class="navbar-nav mr-auto">

        </ul>

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
        <li class="nav-item active">
        </li>

        <li class="nav-item {{ request()->is('showcat') ? 'active' : '' }}">
            <a class="nav-link"  href="{{route('showcat')}}"><i class="icon-paper"></i><span data-i18n="nav.form_layouts.form_layout_basic" class="menu-title">Surveys</span></a>
        </li>

        <li class="nav-item {{ request()->is('addquestion') ? 'active' : '' }}">
            <a class="nav-link"  href="{{route('add-question')}}"><i class="icon-paper"></i><span data-i18n="nav.form_layouts.form_layout_basic" class="menu-title">Add Question</span></a>
        </li>

    </ul>


    <div class="main_content">
        @if (Session::has('message'))
            <div class="alert alert-success patient_success">{{ Session::get('message') }}</div>
        @endif
        @yield('content')
    </div>
<!-- /.content-wrapper -->
</div>

<script src="{{asset('admin/js/script.js')}}"></script>
<script src="{{asset('admin/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
<script src="{{asset('admin/vendor/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
<script src="{{asset('admin/vendor/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('admin/js/sb-admin.min.js')}}"></script>


</body>

</html>

resources/views/admin/question.blade.php
@extends('admin.leftsidebar')

@section('content')
    <div class="container" style="margin-top: 20px">
        <a  href="{{url('/addquestion')}}" class="btn btn-primary" >
            Add Question
        </a>
        <div class="alert alert-primary" role="alert">
            Create question for <a href="/showquestion/{{$question->id}}" class="alert-link">{{$question->cat}}</a>. category.
        </div>
        @if($question->questions->count() > 0)
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Question</th>
                <th>Type</th>
                <th>Delete</th>
                <th>Edit</th>
                <th>Add Answer</th>
                <th>Subquestion</th>
            </tr>
            </thead>
            <tbody>

                @foreach($question->questions_admin as $q)
                    {{--{{dd($question)}}--}}
                <tr>
                    <td> <a href="{{route('addanswer',$q->id)}}"><p class="survey_p answer">{{$q->question}}</p></a></td>
                    <td>{{$q->getCategoryName()}}</td>
                    <td>
                        <form action="{{url('/destroyquestion',$q->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Do You really want to delete this?<p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Delete</button>
                        </form>
                    </td>
                    <td><a href="{{url('editquestion',$q->id)}}" class="btn btn-primary">Edit</a></td>
                    <td>
                        @if($q->type != \App\Question::QUSTOM_QUESTION )
                            <a href="{{url('addanswer',$q->id)}}" class="btn btn-success">Add Answer</a>
                        @endif
                    </td>
                    <td>
                        @if($q->type == \App\Question::WITH_SUBQUESTION)
                            <a href="{{url('addquestion',$q->id)}}" class="btn btn-success">Add Subquestion</a>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @else
            <div class="clearfix  col-md-12">
                <div class="alert alert-warning" role="alert">
                    There Is No Any Questions Yet
                </div>
            </div>
            @endif
    </div>
@endsection

resources/views/admin/showcategory.blade.php
@extends('admin.leftsidebar')

@section('content')

    <div class="container" style="margin-top: 20px">
        <a  href="{{url('/admindashboard/create')}}" class="btn btn-primary" >
            Add Survey
        </a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Survey</th>
            <th>Description</th>
            <th>Delete</th>
            <th>Edit</th>
            <th>Show Questions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($survey as  $sur)
            <tr>
                <td>{{$sur->cat}}</td>
                <td>{{$sur->description}}</td>
                <td>
                    <form action="{{route('admindashboard.destroy',$sur->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        {{--<button class="btn btn-danger" type="submit">Delete</button>--}}
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Do You really want to delete this?<p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Delete</button>
                    </form>
                </td>
                <td><a href="{{route('admindashboard.edit',$sur->id)}}" class="btn btn-primary">Edit</a></td>
                <td>  <a href="{{route('showquestion',$sur->id)}}"><p class="btn btn-success">Show Questions</p></a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection